"""Initial migration

Revision ID: 00923211b494
Revises: 
Create Date: 2025-03-03 22:42:22.271463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00923211b494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_users_email'), 'new_users', ['email'], unique=True)
    op.create_index(op.f('ix_new_users_id'), 'new_users', ['id'], unique=False)
    op.create_index(op.f('ix_new_users_phone'), 'new_users', ['phone'], unique=True)
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('rooms_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['new_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('ix_new_users_phone'), table_name='new_users')
    op.drop_index(op.f('ix_new_users_id'), table_name='new_users')
    op.drop_index(op.f('ix_new_users_email'), table_name='new_users')
    op.drop_table('new_users')
    # ### end Alembic commands ###
