"""Updating houses

Revision ID: ec8ba392db67
Revises: 6bba31eb4f2c
Create Date: 2025-03-13 22:52:43.813846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8ba392db67'
down_revision: Union[str, None] = '6bba31eb4f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'created_at')
    # ### end Alembic commands ###
